
variables:
   CI_DEBUG_TRACE: "false"
   Enviornment: $Enviornment
   Tenant: $Tenant

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
  
stages:
  - pre-rocket
  - build
  - deploy
  - post-deploy

pre-rocket:
  stage: pre-rocket
  script:
    - echo "Env: $Enviornment"
    - echo "Tenant: $Tenant"

build:
  stage: build
  script:
    - echo "Env: $Enviornment"
    - echo "Tenant: $Tenant"

deploy:
  stage: deploy
  script:
    - echo "Env: $Enviornment"
    - echo "Tenant: $Tenant"

post-deploy:
  stage: post-deploy
  script:
    - echo "Env: $Enviornment"
    - echo "Tenant: $Tenant"


# include:
#   - local: 'ansible/gitlab-ci/gitlab-pipeline.yml'
#   # - local: 'ansible/github-actions/github-pipeline.yml'