variables:
  CI_DEBUG_TRACE: "false"

# workflow:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "trigger"'

include:
  - local: include.yml

stages:
  - pre-rocket
  - build
  - deploy
  - post-deploy

before_script:
    - terraform version
    - ansible --version
    - python3 --version

pre-rocket:
  stage: pre-rocket
  image: ansible-playbook
  script:
    - echo "Started pre-rocket stage for $Enviornment for $Tenant"
    - ansible-playbook /pre-rocket/main.yml

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

  script:
    - echo "Building the docker image in build stage:"
    - docker login registry.gitlab.com
    - docker build -t registry.gitlab.com/kpreethiyadav579/system_desgin/ .
    - docker push registry.gitlab.com/kpreethiyadav579/system_desgin

deploy:
  stage: deploy
  script:
    - echo "Deploying to $Enviornment for $Tenant"

post-deploy:
  stage: post-deploy
  script:
    - echo "Completed for $Tenant"