stages:
  - sync
  - build
  - test
  - deploy

variables: 
  terraform_dir: "terraform"
  cloud_name: "aws"

# # Sync GitLab to GitHub Repo
# sync-to-github:
#   stage: sync
#   image: python:3.11
#   variables:
#     REPO_DIR: "repo-sync"

#   before_script:
#     - apt-get update && apt-get install -y git openssh-client
#     - mkdir -p ~/.ssh
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
#     - chmod 600 ~/.ssh/id_ed25519
#     - ssh-keyscan github.com >> ~/.ssh/known_hosts

#   script:
#     - python3 ./project-root/scripts/python/Gitlab-to-Github-SyncRepo.py

build:
  stage: build
  before_script:
    # Install required packages
    - apt-get update -y
    - apt-get install -y wget unzip python3-pip
    # Install Terraform
    - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    - unzip terraform_1.6.6_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - terraform --version
  script:
    - echo "Running Terraform for aws"
    - ansible-playbook ansible/playbooks/terraform.yml

test:
  stage: test
  script:
    - echo "hello this test"

deploy:
  stage: deploy
  script:
    - echo "hello this deploy"