stages:
  - build
  - sync
  - test
  - deploy

variables: 
  terraform_dir: "terraform"
  cloud_name: "aws"

before_script:
  - apt-get update -y
  - apt-get install -y curl unzip python3-pip
  - pip3 install ansible

build:
  stage: build
  before_script:
    # Install required packages
    - apt-get update -y
    - apt-get install -y wget unzip python3-pip
    - apt install ansible -y
    # Install Terraform
    - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    - unzip terraform_1.6.6_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - terraform --version
  script:
    - pwd
    - cd ansible/playbooks/
    - ll
    - ansible-playbook trigger-playbook.yml


# # Sync GitLab to GitHub Repo
# sync-to-github:
#   stage: sync
#   image: python:3.11
#   variables:
#     REPO_DIR: "repo-sync"

#   before_script:
#     - apt-get update && apt-get install -y git openssh-client
#     - mkdir -p ~/.ssh
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
#     - chmod 600 ~/.ssh/id_ed25519
#     - ssh-keyscan github.com >> ~/.ssh/known_hosts

#   script:
#     - python3 ./ansible/scripts/python/Gitlab-to-Github-SyncRepo.py


# test:
#   stage: test
#   script:
#     - echo "hello this test"


deploy_infra:
  stage: deploy
  image: python:3.10

  before_script:
    - pip install ansible
    - ansible-galaxy collection install -r ansible/requirements.yml

  script:
    - cd ansible
    - ansible-playbook playbooks/trigger-playbook.yml
