---
- name: excuting the configurations
  hosts: localhost
  gather_facts: no

  vars: 
    env: "{{ lookup('env', 'Enviornment') }}"
    tenant: "{{ lookup('tenant', 'Tenant') }}"
    access_key: "{{ lookup('access_key', 'AWS_ACCESS_KEY_ID') }}"
    secert_key: "{{ lookup('secert_key', 'AWS_SECRET_ACCESS_KEY') }}"

  tasks:
    - name: testing tasks
      debug:
        msg: "Hello task suning anisble"

    - name: print access_key
      debug:
        msg: "$access_key- and $secert_key"

    - name: excuting terraform
      command: terraform init
      args:
        chdir: terraform
        
 