---
- name: excuting the configurations
  hosts: web
  gather_facts: no

  vars: 
    env: "{{ lookup('env', 'Enviornment') }}"
    tenant: "{{ lookup('tenant', 'Tenant') }}"

  tasks:
    - name: testing tasks
      debug:
        msg: "Hello task suning anisble"