---
- name: executing the configurations
  hosts: localhost
  gather_facts: no

  environment:
    Environment: "{{ lookup('env', 'ENVIRONMENT') }}"
    Tenant: "{{ lookup('env', 'TENANT') }}"

  tasks:        
    - name: executing terraform init
      command: terraform init -input=false
      args:
        chdir: terraform
      register: tf_init

    - name: Show readable output
      debug:
        msg: "{{ tf_init.stdout_lines }}"

    - name: Executing terraform plan
      command:
        argv:
          - terraform
          - plan
          - -out=plan.tf
      args:
        chdir: terraform
      register: tf_plan

    - name: Show readable output
      debug:
        msg: "{{ tf_plan.stdout_lines }}"

    - name: Executing terraform apply
      command:
        argv:
          - terraform
          - apply
          - -auto-approve
          - plan.tf
      args:
        chdir: terraform
      register: tf_apply
    
    - name:  print terraform apply log
      debug:
        msg: "{{ tf_plan.stdout_lines }}"
